function sig = set_er(sig,er,pav)
% Set the extinction ratio of an intensity-modulated optical signal
%
% -------------------------------------------------------------------------
% DESCRIPTION:
% -------------------------------------------------------------------------
% This function sets the extinction ratio and average power of an intensity
% modulated optical signal.
% The signal has to be "clean", i.e. ideally noise-free, at the output of a
% transmitter model.
% The phase information is preserved as in the input signal.
% If one is interested in the actual frequency chirping behaviour of a
% specific modulator type, set directly the extinction ratio through the
% relevant model, e.g. opt_laser_dml, mod_mzm, or other transmitter 
% behavioral model, tx_laser_chirped, mod_linear where the phase is defined 
% through the alpha parameter.
% Note that signals generated by some modules, including the tx module,
% have an infinite extinction ratio. Therefore, even though some phase 
% noise can be imprinted on such signals through the linewidth
% parameter, the phase is undefined whenever a space ('0') is generated. 
% This is obviously not something that can be recovered when introducing a 
% finite extinction ratio to the signal by using the present function.
% Therefore this function is not adapted to this situation. 
%
% -------------------------------------------------------------------------
% FUNCTION CALL:
% -------------------------------------------------------------------------
% params_tx.type = 'ook_nrz';
% params_tx.emission_frequency = reference_frequency;
% params_tx.power = 1.0e-3;
% params_tx.linewidth = 0;
% params_tx.bit_pattern = bit_pattern;
% params_tx.rise_time = 1/symbol_rate/4;
% sig = tx(params_tx);
% er_db = 10;
% pav_dbm = 0;
% sig = set_er(sig,er_db,pav_dbm);
%
% -------------------------------------------------------------------------
% INPUTS:
% -------------------------------------------------------------------------
% sig               input optical signal [optical signal structure]
%                       
%                       The signal should ideally be free from intensity
%                       noise, as obtained from the use of the tx function,
%                       for instance
%
%                       Read the description above in case the signal
%                       presents some phase noise together with an infinite
%                       extinction ratio.
%
%                       The signal should be polarised along the -x
%                       direction.
%
% er                target extinction ratio, in dB [real scalar]
%
%                       The extinction ratio is defined as ER = P1/P0
%                       where P0 is the space power level and P1 the mark
%                       power level.
%
% pav               target average power, in dBm [real scalar]
%                      
% -------------------------------------------------------------------------
% OUTPUTS:
% -------------------------------------------------------------------------
% sig               output optical signal [optical signal structure]
%                      
%                       The signal is still polarised along the -x
%                       direction.
%
% -------------------------------------------------------------------------
% GLOBAL:
% -------------------------------------------------------------------------
%
%
% -------------------------------------------------------------------------
% -------------------------------------------------------------------------

if mean(abs(sig.y)) > 0
    error('set_er: input signal is assumed to be polarised along -x');
end


pin = abs(sig.x).^2;
% Input signal power Pin(t)
% The signal is assumed to be polarised along -x.

phi = angle(sig.x);
% Input signal phase

pmax = max(pin);
pmin = min(pin);

pnorm = (pin - pmin)/(pmax - pmin);
% The input signal power is now normalised to [0 1]: Pnorm(t)

er = 10.^(er/10);
% Target extinction ratio, in linear scale

pav = 10^(pav/10)*1.0e-3;
% Target average power, in W

pnorm_bar = mean(pnorm);
% Average of Pnorm(t)

P0 = pav/((er - 1)*pnorm_bar + 1);
P1 = er*P0;
% Space and mark levels satisfying the target average power and extinction
% ratio conditions

pout = (P1 - P0)*pnorm + P0;
% Output power

sig.x = sqrt(pout).*exp(1j*phi);
% Output signal. The phase is preserved. Check function description.

end